import type { PowerCard } from "@/types"

export const MINOR_CARDS: Array<PowerCard> = [
  {
    name: 'Savage Mawbeasts',
    cost: 0,
    speed: 'Slow',
    elements: [
      'Fire',
      'Animal',
    ],
    description: 'If target land is Jungle / Wetland, 1 Fear and 1 Damage. -If you have- 3 Animal: 1 Damage.',
  },
  {
    name: 'Shadows of the Burning Forest',
    cost: 0,
    speed: 'Slow',
    elements: [
      'Moon',
      'Fire',
      'Plant',
    ],
    description: '2 Fear. If target land is Mountain / Jungle, Push 1 Explorer and 1 Town.',
  },
  {
    name: 'Sap the Strength of Multitudes',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Water',
      'Animal',
    ],
    description: 'Defend 5. -If you have- 1 Air: Increase this Power\'s Range by 1',
  },
  {
    name: 'Drift down into Slumber',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Air',
      'Earth',
      'Plant',
    ],
    description: 'Defend 1. If target land is Jungle / Sands, instead, Defend 4.',
  },
  {
    name: 'Land of Haunts and Embers',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Moon',
      'Fire',
      'Air',
    ],
    description: '2 Fear. Push up to 2 Explorer / Town. If target land has Blight, +2 Fear. Push up to 2 more Explorer / Town. Add 1 Blight.',
  },
  {
    name: 'Call to Isolation',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Sun',
      'Air',
      'Animal',
    ],
    description: 'Push 1 Explorer / Town per Dahan. -or- Push 1 Dahan.',
  },
  {
    name: 'Gift of Constancy',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Sun',
      'Earth',
    ],
    description: 'Target Spirit gains 2 Energy. At end of turn, target Spirit may Reclaim 1 Power Card instead of discarding it. If you target another Spirit, you may also Reclaim 1 Power Card instead of discarding it.',
  },
  {
    name: 'Enticing Splendor',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Sun',
      'Air',
      'Plant',
    ],
    description: 'Gather 1 Explorer / Town. -or- Gather up to 2 Dahan.',
  },
  {
    name: 'Gift of Living Energy',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Sun',
      'Fire',
      'Plant',
    ],
    description: 'Target Spirit gains 1 Energy, +1 Energy if target Spirit is not yourself. If you have at least 2 SacredSite, target Spirit gains +1 Energy.',
  },
  {
    name: 'Gift of Power',
    cost: 0,
    speed: 'Slow',
    elements: [
      'Moon',
      'Water',
      'Earth',
      'Plant',
    ],
    description: 'Gain a Minor Power Card.',
  },
  {
    name: 'Gnawing Rootbiters',
    cost: 0,
    speed: 'Slow',
    elements: [
      'Earth',
      'Animal',
    ],
    description: 'Push up to 2 Town.',
  },
  {
    name: 'Lure of the Unknown',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Moon',
      'Fire',
      'Air',
      'Plant',
    ],
    description: 'Gather 1 Explorer / Town',
  },
  {
    name: 'Rain of Blood',
    cost: 0,
    speed: 'Slow',
    elements: [
      'Air',
      'Water',
      'Animal',
    ],
    description: '2 Fear. If target land has at least 2 Town / City, +1 Fear.',
  },
  {
    name: 'Reaching Grasp',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Sun',
      'Air',
      'Water',
    ],
    description: 'Target Spirit gets +2 Range with all their Powers.',
  },
  {
    name: 'Gold\'s Allure',
    cost: 0,
    speed: 'Slow',
    elements: [
      'Fire',
      'Earth',
      'Animal',
    ],
    description: 'Gather 1 Explorer. and 1 Town. Add 1 Strife.',
  },
  {
    name: 'Here there be Monsters',
    cost: 0,
    speed: 'Slow',
    elements: [
      'Moon',
      'Air',
      'Animal',
    ],
    description: 'You may Push 1 Explorer / Town / Dahan. 2 Fear. If target land has any Beasts, 1 Fear.',
  },
  {
    name: 'Portents of Disaster',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Sun',
      'Moon',
      'Air',
    ],
    description: '2 Fear. The next time an Invader is destroyed in target land this turn, 1 Fear.',
  },
  {
    name: 'Growth through Sacrifice',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Moon',
      'Fire',
      'Water',
      'Plant',
    ],
    description: 'Destroy 1 of your Presence. Target Spirit chooses to either: Remove 1 Blight from one of their lands. -or- Add 1 Presence to one of their lands. -If you have- 2 Sun: They may do both, in the same land.',
  },
  {
    name: 'Swarming Wasps',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Fire',
      'Air',
      'Animal',
    ],
    description: 'Add 1 Beasts. -or- If target land has Beasts, Push up to 2 Explorer.',
  },
  {
    name: 'Animated Wrackroot',
    cost: 0,
    speed: 'Slow',
    elements: [
      'Moon',
      'Fire',
      'Plant',
    ],
    description: '1 Fear. Destroy 1 Explorer. -or- Add 1 Wilds.',
  },
  {
    name: 'Promises of Protection',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Sun',
      'Earth',
      'Animal',
    ],
    description: 'Gather up to 2 Dahan. Dahan have +2 Health while in target land.',
  },
  {
    name: 'Call to Ferocity',
    cost: 0,
    speed: 'Slow',
    elements: [
      'Sun',
      'Fire',
      'Earth',
    ],
    description: 'Gather up to 3 Dahan. -or- If target land has Dahan, 1 Fear and Push 1 Explorer and 1 Town.',
  },
  {
    name: 'Twilight Fog brings Madness',
    cost: 0,
    speed: 'Slow',
    elements: [
      'Sun',
      'Moon',
      'Air',
      'Water',
    ],
    description: 'Add 1 Strife. Push 1 Dahan. Each remaining Dahan takes 1 Damage.',
  },
  {
    name: 'Hazards Spread Across The Island',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Fire',
      'Air',
      'Earth',
      'Plant',
    ],
    description: 'Choose a type of token from Badlands / Beasts / Disease / Strife / Wilds that exists in an adjacent land; choosing Disease costs 1 energy. Add 1 of that type of token to target land.',
  },
  {
    name: 'Carapaced Land',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Earth',
      'Plant',
      'Animal',
    ],
    description: 'If targeting a land with Beasts, this Power has +1 Range. Defend 3. -If you have- 2 Earth: Defend +3.',
  },
  {
    name: 'Call To Guard',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Sun',
      'Air',
      'Earth',
    ],
    description: 'Gather up to 1 Dahan. Then, if Dahan are present, either: Defend 1 per Dahan. -or- After Invaders are added or moved to target land, 1 Damage to each added or moved Invader.',
  },
  {
    name: 'Gift of Nature\'s Connection',
    cost: 0,
    speed: 'Fast',
    elements: [
      '',
    ],
    description: 'Target Spirit gains either 2 Energy or 2 of a single Element (their choice). If you target another Spirit, you gain an Element of your choice.',
  },
  {
    name: 'Mesmerized Tranquility',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Water',
      'Earth',
      'Animal',
    ],
    description: 'Isolate target land. Each Invader does -1 Damage.',
  },
  {
    name: 'Territorial Strife',
    cost: 0,
    speed: 'Slow',
    elements: [
      'Sun',
      'Fire',
      'Animal',
    ],
    description: '3 Damage to Explorer / Town. -or- Add 1 Strife.',
  },
  {
    name: 'Sear Anger Into The Wild Lands',
    cost: 0,
    speed: 'Slow',
    elements: [
      'Sun',
      'Fire',
      'Plant',
    ],
    description: 'Add 1 Badlands. -or- If Wilds and Invaders are present, 1 Fear and 1 Damage.',
  },
  {
    name: 'Strong And Constant Currents',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Sun',
      'Water',
      'Earth',
    ],
    description: 'Push 1 Explorer / Town to an adjacent Coastal land. -or- Move up to 2 Dahan between target land and one other Coastal land. -If you have- 2 Water: You may do both.',
  },
  {
    name: 'Sucking Ooze',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Moon',
      'Water',
      'Earth',
    ],
    description: '2 Fear if Invaders are present. Isolate target land.',
  },
  {
    name: 'Terror Turns To Madness',
    cost: 0,
    speed: 'Slow',
    elements: [
      'Moon',
      'Air',
      'Water',
    ],
    description: 'If the Terror Level is... Terror Level 1: 3 Fear. Terror Level 2: 2 Fear or add 1 Strife. Terror Level 3: Add 1 Strife.',
  },
  {
    name: 'Treacherous Waterways',
    cost: 0,
    speed: 'Fast',
    elements: [
      'Fire',
      'Water',
      'Earth',
    ],
    description: 'Add 1 Wilds. -or- Push 1 Explorer.',
  },
  {
    name: 'Flow Downriver, Blow Downwind',
    cost: 0,
    speed: 'Slow',
    elements: [
      'Air',
      'Water',
      'Plant',
    ],
    description: 'Push up to 1 Blight / Explorer / Town.',
  },
  {
    name: 'Weep For What Is Lost',
    cost: 0,
    speed: 'Slow',
    elements: [
      'Fire',
      'Water',
      'Animal',
    ],
    description: '1 Fear per type of Invader present. Push up to 1 Explorer / Town per Blight.',
  },
  {
    name: 'Voracious Growth',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Water',
      'Plant',
    ],
    description: '2 Damage. -or- Remove 1 Blight.',
  },
  {
    name: 'Rouse the Trees and Stones',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Fire',
      'Earth',
      'Plant',
    ],
    description: '2 Damage. Push 1 Explorer.',
  },
  {
    name: 'Encompassing Ward',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Sun',
      'Water',
      'Earth',
    ],
    description: 'Defend 2 in every land where target Spirit has Presence.',
  },
  {
    name: 'Song of Sanctity',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Sun',
      'Water',
      'Plant',
    ],
    description: 'If target land has 1 Explorer, Push all Explorer. Otherwise, remove 1 Blight.',
  },
  {
    name: 'Uncanny Melting',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Sun',
      'Moon',
      'Water',
    ],
    description: 'If Invaders are present, 1 Fear. If target land is Sands / Wetland, remove 1 Blight',
  },
  {
    name: 'Steam Vents',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Fire',
      'Air',
      'Water',
      'Earth',
    ],
    description: 'Destroy 1 Explorer. -If you have- 3 Earth: You may instead destroy 1 Town.',
  },
  {
    name: 'Veil the Night\'s Hunt',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Moon',
      'Air',
      'Animal',
    ],
    description: 'Each Dahan deals 1 Damage to a different Invader. -or- Push up to 3 Dahan.',
  },
  {
    name: 'Elemental Boon',
    cost: 1,
    speed: 'Fast',
    elements: [
      '',
    ],
    description: 'Target Spirit gains 3 different Elements of their choice. If you target another Spirit, you also gain the chosen Elements.',
  },
  {
    name: 'Devouring Ants',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Sun',
      'Earth',
      'Animal',
    ],
    description: '1 Fear. 1 Damage. Destroy 1 Dahan. If target land is Jungle / Sands, +1 Damage.',
  },
  {
    name: 'Dark and Tangled Woods',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Moon',
      'Earth',
      'Plant',
    ],
    description: '2 Fear. If target land is Mountain / Jungle, Defend 3.',
  },
  {
    name: 'Nature\'s Resilience',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Earth',
      'Plant',
      'Animal',
    ],
    description: 'Defend 6. -If you have- 2 Water: You may instead remove 1 Blight.',
  },
  {
    name: 'Visions of Fiery Doom',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Moon',
      'Fire',
    ],
    description: '1 Fear. Push 1 Explorer / Town. -If you have- 2 Fire: +1 Fear.',
  },
  {
    name: 'Pull Beneath the Hungry Earth',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Moon',
      'Water',
      'Earth',
    ],
    description: 'If target land has your Presence, 1 Fear and 1 Damage. If target land is Sands / Wetland, 1 Damage.',
  },
  {
    name: 'Call of the Dahan Ways',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Moon',
      'Water',
      'Animal',
    ],
    description: 'Replace 1 Explorer with 1 Dahan. -If you have- 2 Moon: You may instead replace 1 Town with 1 Dahan.',
  },
  {
    name: 'Call to Bloodshed',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Sun',
      'Fire',
      'Animal',
    ],
    description: '1 Damage per Dahan. -or- Gather up to 3 Dahan.',
  },
  {
    name: 'Call to Migrate',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Fire',
      'Air',
      'Animal',
    ],
    description: 'Gather up to 3 Dahan. Push up to 3 Dahan.',
  },
  {
    name: 'Call to Tend',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Water',
      'Plant',
      'Animal',
    ],
    description: 'Remove 1 Blight. -or- Push up to 3 Dahan.',
  },
  {
    name: 'Quicken the Earth\'s Struggles',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Moon',
      'Fire',
      'Earth',
      'Animal',
    ],
    description: '1 Damage to each Town / City. -or- Defend 10.',
  },
  {
    name: 'Delusions of Danger',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Sun',
      'Moon',
      'Air',
    ],
    description: 'Push 1 Explorer. -or- 2 Fear.',
  },
  {
    name: 'Drought',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Sun',
      'Fire',
      'Earth',
    ],
    description: 'Destroy 3 Town. 1 Damage to each Town / City. Add 1 Blight. -If you have- 3 Sun: Destroy 1 City.',
  },
  {
    name: 'Entrancing Apparitions',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Moon',
      'Air',
      'Water',
    ],
    description: 'Defend 2. If no Invaders are present, gather up to 2 Explorer.',
  },
  {
    name: 'Purifying Flame',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Sun',
      'Fire',
      'Air',
      'Plant',
    ],
    description: '1 Damage per Blight. If target land is Mountain / Sands, you may instead remove 1 Blight.',
  },
  {
    name: 'Inflame the Fires of Life',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Moon',
      'Fire',
      'Plant',
      'Animal',
    ],
    description: 'Add 1 Disease. -or\'- 1 Fear. Add 1 Strife. -If you have- 3 Animal: You may do both.',
  },
  {
    name: 'Fire in the Sky',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Sun',
      'Fire',
      'Air',
    ],
    description: '2 Fear. Add 1 Strife',
  },
  {
    name: 'Fleshrot Fever',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Fire',
      'Air',
      'Water',
      'Animal',
    ],
    description: '1 Fear. Add 1 Disease.',
  },
  {
    name: 'Guardian Serpents',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Sun',
      'Moon',
      'Earth',
      'Animal',
    ],
    description: 'Add 1 Beasts in one of target Spirit\'s lands. If target Spirit has a SacredSite in that land: Defend 4 there.',
  },
  {
    name: 'Infested Aquifers',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Moon',
      'Water',
      'Earth',
      'Animal',
    ],
    description: 'If target land has any Disease, 1 Damage to each Invader. -or- If target land is Mountain / Wetland, 1 Fear and add 1 Disease.',
  },
  {
    name: 'Poisoned Dew',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Fire',
      'Water',
      'Plant',
    ],
    description: 'Destroy 1 Explorer. If target land is Jungle / Wetland, destroy all Explorer.',
  },
  {
    name: 'Prowling Panthers',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Moon',
      'Fire',
      'Animal',
    ],
    description: '1 Fear. Add 1 Beasts. -or- If target land has Beasts, destroy 1 Explorer / Town.',
  },
  {
    name: 'Renewing Rain',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Water',
      'Earth',
      'Plant',
    ],
    description: 'If target land is Jungle / Sands, remove 1 Blight. -If you have- 3 Plant: Add 1 Wilds.',
  },
  {
    name: 'Rites of the Land\'s Rejection',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Moon',
      'Fire',
      'Earth',
    ],
    description: 'Invaders do not Build in target land this turn. 1 Fear per Town / City or 1 Fear per Dahan, whichever is less. -or- Push up to 3 Dahan.',
  },
  {
    name: 'Pact of the Joined Hunt',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Sun',
      'Plant',
      'Animal',
    ],
    description: 'Target Spirit Gathers 1 Dahan into one of their lands. 1 Damage in that land per Dahan present.',
  },
  {
    name: 'Razor-Sharp Undergrowth',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Moon',
      'Plant',
    ],
    description: 'Destroy 1 Explorer and 1 Dahan. Add 1 Wilds. Defend 2.',
  },
  {
    name: 'Scour the Land',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Air',
      'Earth',
    ],
    description: 'Destroy 3 Town and all Explorer. Add 1 Blight. -If you have- 3 Air: This power may be Fast.',
  },
  {
    name: 'Sky Stretches to Shore',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Sun',
      'Air',
      'Water',
      'Earth',
    ],
    description: 'This turn, target Spirit may use 1 Slow Power as if it were Fast, or vice versa. Target Spirit gains +3 Range for targeting Coastal lands only.',
  },
  {
    name: 'Absorb Corruption',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Sun',
      'Earth',
      'Plant',
    ],
    description: 'Gather 1 Blight. -or- Pay 1 Energy to remove 1 Blight. -If you have- 2 Plant: You may do both.',
  },
  {
    name: 'Call to Trade',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Air',
      'Water',
      'Earth',
      'Plant',
    ],
    description: 'You may Gather 1 Dahan. If the Terror Level is 2 or lower, Gather 1 Town and the first Ravage in target land this turn becomes a Build there instead.',
  },
  {
    name: 'Confounding Mists',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Air',
      'Water',
    ],
    description: 'Defend 4. -or- Each Invader added to target land this turn may be immediately Pushed to any adjacent land.',
  },
  {
    name: 'Cycles of Time and Tide',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Sun',
      'Moon',
      'Water',
    ],
    description: 'If there are Dahan, add 1 Dahan. If there are no Dahan, remove 1 Blight.',
  },
  {
    name: 'Disorienting Landscape',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Moon',
      'Air',
      'Plant',
    ],
    description: 'Push 1 Explorer. If target land is Mountain / Jungle, add 1 Wilds.',
  },
  {
    name: 'Elusive Ambushes',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Sun',
      'Fire',
      'Water',
    ],
    description: '1 Damage. -or- Defend 4.',
  },
  {
    name: 'Tormenting Rotflies',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Air',
      'Plant',
      'Animal',
    ],
    description: 'Add 1 Disease. -or- If target land has Invaders, 2 Fear. If Disease is present, +1 Fear. If Blight is present, +1 Fear.',
  },
  {
    name: 'Teeming Rivers',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Sun',
      'Water',
      'Plant',
      'Animal',
    ],
    description: 'If target land has no Blight, add 1 Beasts. If target land has exactly 1 Blight, remove it.',
  },
  {
    name: 'Spur on with Words of Fire',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Sun',
      'Fire',
      'Air',
    ],
    description: 'If you target a Spirit other than yourself, they gain +1 Energy. Target Spirit may immediately play another Power Card by paying its cost. (If it is Slow, it does not resolve until later.)',
  },
  {
    name: 'Bats Scout For Raids By Darkness',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Moon',
      'Air',
      'Animal',
    ],
    description: 'For each Dahan, 1 Damage to Town / City. -or- 1 Fear. Gather up to 2 Dahan.',
  },
  {
    name: 'Birds Cry Warning',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Sun',
      'Air',
      'Animal',
    ],
    description: 'The next time Dahan would be Destroyed in target land, Destroy 2 fewer Dahan. -or- Push up to 3 Dahan.',
  },
  {
    name: 'Blood Draws Predators',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Sun',
      'Fire',
      'Water',
      'Animal',
    ],
    description: 'After the next time Invaders are Destroyed in target land: Add 1 Beasts, then 1 Damage per Beasts (max. 3 Damage).',
  },
  {
    name: 'Desiccating Winds',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Fire',
      'Air',
      'Earth',
    ],
    description: 'If target land has Badlands, 1 Damage. Add 1 Badlands.',
  },
  {
    name: 'Dry Wood Explodes In Smoldering Splinters',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Fire',
      'Air',
      'Plant',
    ],
    description: 'You may spend 1 Energy to make this Power Fast. 2 Fear. 1 Damage.',
  },
  {
    name: 'Entrap The Forces Of Corruption',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Earth',
      'Plant',
      'Animal',
    ],
    description: 'Gather up to 1 Blight. Isolate target land. When Blight is added to target land, it doesn\'t cascade.',
  },
  {
    name: 'Domesticated Animals Go Berserk',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Moon',
      'Fire',
      'Animal',
    ],
    description: '1 Fear. Defend 5. -If you have- 3 Moon: Add 1 Beasts.',
  },
  {
    name: 'Dire Metamorphosis',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Moon',
      'Air',
      'Earth',
      'Animal',
    ],
    description: '1 Fear. 1 Damage. 1 Damage to Dahan. Add 1 Badlands, 1 Beasts, 1 Disease, 1 Strife, 1 Wilds, and 1 Blight.',
  },
  {
    name: 'Skies Herald The Season Of Return',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Sun',
      'Moon',
      'Plant',
      'Animal',
    ],
    description: 'A Spirit with Presence on target board may add 1 of their Destroyed Presence. Gather up to 2 Dahan. Push 1 Blight.',
  },
  {
    name: 'Gift of Twinned Days',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Sun',
      'Moon',
    ],
    description: 'Once this turn, target Spirit may Repeat the lowest-cost Power Card they have in play by paying it\'s cost again. You may do likewise.',
  },
  {
    name: 'Haunted By Primal Memories',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Moon',
      'Air',
      'Earth',
    ],
    description: '1 Fear. Defend 3. If Beasts are present, +2 Fear.',
  },
  {
    name: 'Like Calls to Like',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Sun',
      'Water',
      'Plant',
    ],
    description: 'If target land has Explorer, Gather up to 1 Explorer. Do likewise for Town, Dahan, Blight, and Beasts.',
  },
  {
    name: 'Unquenchable Flames',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Moon',
      'Fire',
      'Earth',
    ],
    description: '1 Fear. 1 Damage to Town / City. Invaders do not heal Damage at end of turn. -If you have- 2 Fire: Add 1 Badlands.',
  },
  {
    name: 'Renewing Boon',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Sun',
      'Earth',
      'Plant',
    ],
    description: 'Choose a land where you and target Spirit both have Presence. In that land: Remove 1 Blight, and target Spirit may add 1 of their Destroyed Presence.',
  },
  {
    name: 'Scream Disease Into The Wind',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Air',
      'Water',
      'Animal',
    ],
    description: 'Target Spirit gets +1 Range with all their Powers. Once this turn, after target Spirit uses a Power targeting a land, they may add 1 Disease to that land. (Hand them a Disease token as a reminder.)',
  },
  {
    name: 'Set Them On An Ever-Twisting Trail',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Air',
      'Plant',
      'Animal',
    ],
    description: 'Gather or Push 1 Explorer. Isolate target land.',
  },
  {
    name: 'Sunset\'s Fire Flows Across The Land',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Sun',
      'Moon',
      'Fire',
      'Water',
    ],
    description: '1 Fear. 1 Damage. You may pay 1 Energy to deal 1 Damage in an adjacent land.',
  },
  {
    name: 'The Shore Seethes With Hatred',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Fire',
      'Water',
      'Earth',
      'Plant',
    ],
    description: '1  Fear. Add 1 Badlands and 1 Wilds.',
  },
  {
    name: 'Thriving Chokefungus',
    cost: 1,
    speed: 'Slow',
    elements: [
      'Moon',
      'Water',
      'Plant',
    ],
    description: 'Add 1 Disease and 1 Badlands.',
  },
  {
    name: 'Favor Of The Sun And Star-Lit Dark',
    cost: 1,
    speed: 'Fast',
    elements: [
      'Sun',
      'Moon',
      'Plant',
    ],
    description: 'Defend 4. Push up to 1 Blight. -If you have- 2 Sun: 1 Fear',
  },
]
export const MAJOR_CARDS: Array<PowerCard> = [
  {
    name: 'The Trees and Stones Speak of War',
    cost: 2,
    speed: 'Fast',
    elements: [
      'Sun',
      'Earth',
      'Plant',
    ],
    description: 'For each Dahan in target land, 1 Damage and Defend 2. -If you have- 2 Sun, 2 Earth, 2 Plant: You may Push up to 2 Dahan, moving each\'s Defend with them.',
  },
  {
    name: 'Entwined Power',
    cost: 2,
    speed: 'Fast',
    elements: [
      'Moon',
      'Water',
      'Plant',
    ],
    description: 'You and target Spirit may use each other\'s Presence to target Powers. Target Spirit gains a Power Card. You gain one of the power Cards they did not keep. -If you have- 2 Water, 4 Plant: You and target Spirit each gain 3 Energy and may gift the other 1 Power from hand.',
  },
  {
    name: 'Flow like Water, Reach like Air',
    cost: 2,
    speed: 'Fast',
    elements: [
      'Air',
      'Water',
    ],
    description: 'Target Spirit gets +2 Range with all Powers. Target Spirit may Push 1 of their Presence to an adjacent land, bringing up to 2 Explorer, 2 Town and 2 Dahan along with it. -If you have- 2 Air, 2 Water: The moved Presence may also bring along up to 2 City and up to 2 Blight.',
  },
  {
    name: 'Savage Transformation',
    cost: 2,
    speed: 'Slow',
    elements: [
      'Moon',
      'Animal',
    ],
    description: '2 Fear. Replace 1 Explorer with 1 Beasts. -If you have- 2 Moon, 3 Animal: Replace 1 additional Explorer with 1 Beasts in either target or adjacent land.',
  },
  {
    name: 'Tigers Hunting',
    cost: 2,
    speed: 'Fast',
    elements: [
      'Sun',
      'Moon',
      'Animal',
    ],
    description: '2 Fear. Add 1 Beasts. Gather up to 1 Beasts. 1 Damage per Beasts. Push up to 2 Beasts. -If you have- 2 Sun, 2 Moon, 3 Animal: 1 Damage in an adjacent land without Blight, and +1 Damage per Beasts there.',
  },
  {
    name: 'Unleash a Torrent of the Self\'s Own Essence',
    cost: 2,
    speed: 'Fast',
    elements: [
      'Sun',
      'Moon',
      'Fire',
      'Water',
    ],
    description: 'Gain 4 energy. You may forget a power card to gain 4 more energy. -or- Pay X energy (min. 1) to deal X damage in a land at 0 Range.  -If you have- 2 Sun, 3 Fire: You may do both.',
  },
  {
    name: 'Bargains of Power and Protection',
    cost: 2,
    speed: 'Fast',
    elements: [
      'Sun',
      'Water',
      'Earth',
      'Animal',
    ],
    description: 'Remove 1 of your Presence on the island from the game, setting it on the Reminder Card. From now on: each Dahan within 1 Range of your Presence provides Defend 1 in its land, and you gain 1 less Energy each turn. (This effect stacks if used multiple times) -If you have- 3 Sun, 2 Water, 2 Earth: The Presence instead comes from your Presence track.',
  },
  {
    name: 'Poisoned Land',
    cost: 3,
    speed: 'Slow',
    elements: [
      'Earth',
      'Plant',
      'Animal',
    ],
    description: '1 Fear. 7 Damage. Add 1 Blight and destroy all Dahan. -If you have- 3 Earth, 2 Plant, 2 Animal: For each Blight then present, +1 Fear and +4 Damage.',
  },
  {
    name: 'Powerstorm',
    cost: 3,
    speed: 'Fast',
    elements: [
      'Sun',
      'Fire',
      'Air',
    ],
    description: 'Target Spirit gains 3 Energy. Once this turn, target may Repeat a Power Card by paying its cost again. -If you have- 2 Sun, 2 Fire, 3 Air: Target may Repeat up to 2 more Power Cards by paying their costs.',
  },
  {
    name: 'The Jungle Hungers',
    cost: 3,
    speed: 'Slow',
    elements: [
      'Moon',
      'Plant',
    ],
    description: 'Destroy all Explorer and all Town. Destroy all Dahan. -If you have- 2 Moon, 3 Plant: Destroy 1 City. Do not destroy any Dahan.',
  },
  {
    name: 'Vigor of the Breaking Dawn',
    cost: 3,
    speed: 'Fast',
    elements: [
      'Sun',
      'Animal',
    ],
    description: '2 Damage per Dahan in target land. -If you have- 3 Sun, 2 Animal: You may Push up to 2 Dahan. In lands you Pushed Dahan to, 2 Damage per Dahan.',
  },
  {
    name: 'Vengeance of the Dead',
    cost: 3,
    speed: 'Fast',
    elements: [
      'Moon',
      'Fire',
      'Animal',
    ],
    description: '3 Fear. After each effect that destroys Town / City / Dahan in target land, 1 Damage per Town / City / Dahan destroyed. -If you have- 3 Animal: Damage from this Power may be dealt into adjacent lands.',
  },
  {
    name: 'Wrap in Wings of Sunlight',
    cost: 3,
    speed: 'Fast',
    elements: [
      'Sun',
      'Air',
      'Animal',
    ],
    description: 'Move up to 5 Dahan from target land to any land. Defend 5 in that land. -If you have- 2 Sun, 2 Air, 2 Animal: First, Gather up to 3 Dahan.',
  },
  {
    name: 'Winds of Rust and Atrophy',
    cost: 3,
    speed: 'Fast',
    elements: [
      'Air',
      'Water',
      'Animal',
    ],
    description: '1 Fear and Defend 6. Replace 1 City with 1 Town or 1 Town with 1 Explorer. -If you have- 3 Air, 3 Water, 2 Animal: Repeat this Power.',
  },
  {
    name: 'Infinite Vitality',
    cost: 3,
    speed: 'Fast',
    elements: [
      'Earth',
      'Plant',
      'Animal',
    ],
    description: 'Dahan have +4 Health while in target land. Whenever Blight would be added to target land, instead leave it on the card. -If you have- 4 Earth: Dahan ignore Damage and Destruction effects. Remove 1 Blight from target or adjacent land.',
  },
  {
    name: 'Pent-Up Calamity',
    cost: 3,
    speed: 'Fast',
    elements: [
      'Moon',
      'Fire',
      'Earth',
      'Plant',
      'Animal',
    ],
    description: 'Add 1 Disease and 1 Strife. -or- Remove any number of Beasts / Disease / Strife / Wilds. For each token removed, 1 Fear and 3 Damage. -If you have- 2 Moon, 3 Fire: If you have removed tokens, return up to 2 of them. Otherwise, add 2 Strife.',
  },
  {
    name: 'Pyroclastic Flow',
    cost: 3,
    speed: 'Fast',
    elements: [
      'Fire',
      'Air',
      'Earth',
    ],
    description: '2 Damage. Destroy all Explorer. If target land is Jungle / Wetland, add 1 Blight. -If you have- 2 Fire, 3 Air, 2 Earth: +4 Damage. Add 1 Wilds.',
  },
  {
    name: 'Smothering Infestation',
    cost: 3,
    speed: 'Slow',
    elements: [
      'Water',
      'Plant',
    ],
    description: 'Add 1 Disease. If target land is Jungle / Wetland, 2 Fear and 3 Damage. -If you have- 2 Water, 2 Plant: 1 Damage to each Invader.',
  },
  {
    name: 'Angry Bears',
    cost: 3,
    speed: 'Slow',
    elements: [
      'Sun',
      'Fire',
      'Animal',
    ],
    description: '2 Fear. 2 Damage. If no Beasts are present, add 1 Beasts. Otherwise, +2 Damage, and Push up to 1 Beasts.  -If you have- 2 Fire, 3 Animal: 1 Fear and destroy 1 Explorer / Town in an adjacent land with Beasts.',
  },
  {
    name: 'Vanish Softly Away, Forgotten by All',
    cost: 3,
    speed: 'Slow',
    elements: [
      'Moon',
      'Air',
    ],
    description: 'Remove 1 Invader and 1 Explorer / Town. -or- Remove all Damaged Invaders. Adversary or Scenario rules that prevent or alter Removal do not affect this Power.  -If you have- 3 Moon, 3 Air: In any 2 lands with 4 or more Invaders: Remove 1 Invader.',
  },
  {
    name: 'Settle Into Hunting-Grounds',
    cost: 3,
    speed: 'Fast',
    elements: [
      'Moon',
      'Fire',
      'Plant',
      'Animal',
    ],
    description: 'Your Presence may count as Badlands and Beasts. (Decide per Presence, per action.) Your Presence cannot move. -If you have- 2 Plant, 3 Animal: 2 Fear and 2 Damage in one of your lands.',
  },
  {
    name: 'Voice of Command',
    cost: 3,
    speed: 'Fast',
    elements: [
      'Sun',
      'Air',
    ],
    description: '1 Damage per Dahan / Explorer, to Town / City only. Defend 2. During Ravage actions, Explorer fight alongside Dahan. (Deal / take damage at the same time, and to / from the same sources.) -If you have- 3 Sun, 2 Air: First, Gather up to 2 Explorer / Town / Dahan',
  },
  {
    name: 'Storm-Swath',
    cost: 3,
    speed: 'Slow',
    elements: [
      'Fire',
      'Air',
      'Water',
    ],
    description: '2 Fear. In both origin land and target land: 1 Damage to each Invader. -If you have- 2 Fire, 3 Air, 2 Water: +1 Fear. This Power has +1 Range. In a land adjacent to both origin and target, 1 Damage to each Invader. In lands where you did Damage, destroy 1 town.',
  },
  {
    name: 'Sleep and Never Waken',
    cost: 3,
    speed: 'Fast',
    elements: [
      'Moon',
      'Air',
      'Earth',
      'Animal',
    ],
    description: 'Invaders skip all Actions in target land. 1 Fear per 2 Explorer this Power removes. Remove up to 2 Explorer. -If you have- 3 Moon, 2 Air, 2 Animal: Remove up to 6 Explorer from among your lands.',
  },
  {
    name: 'Trees Radiate Celestial Brilliance',
    cost: 3,
    speed: 'Fast',
    elements: [
      'Sun',
      'Moon',
      'Plant',
    ],
    description: '3 Fear. Defend 6. Invaders skip the next build. (In target land this turn.) -If you have- 3 Sun, 2 Moon, 2 Plant: 1 Damage per Sun you have.',
  },
  {
    name: 'Thickets Erupt with Every Touch of Breeze',
    cost: 3,
    speed: 'Fast',
    elements: [
      'Air',
      'Plant',
    ],
    description: '2 Damage. Then either: Add 3 Wilds. -or- Remove 1 Blight. -If you have- 3 Plant: 1 Fear. +2 Damage.',
  },
  {
    name: 'Accelerated Rot',
    cost: 4,
    speed: 'Slow',
    elements: [
      'Sun',
      'Water',
      'Plant',
    ],
    description: '2 Fear. 4 Damage. -If you have- 3 Sun, 2 Water, 3 Plant: +5 Damage. Remove 1 Blight.',
  },
  {
    name: 'Terrifying Nightmares',
    cost: 4,
    speed: 'Fast',
    elements: [
      'Moon',
      'Air',
    ],
    description: '2 Fear. Push up to 4 Explorer / Town. -If you have- 4 Moon: +4 Fear.',
  },
  {
    name: 'Paralyzing Fright',
    cost: 4,
    speed: 'Fast',
    elements: [
      'Air',
      'Earth',
    ],
    description: '4 Fear. Invaders skip all Actions in target land this turn. -If you have- 2 Air, 3 Earth: +4 Fear.',
  },
  {
    name: 'The Land Thrashes in Furious Pain',
    cost: 4,
    speed: 'Slow',
    elements: [
      'Moon',
      'Fire',
      'Earth',
    ],
    description: '2 Damage per Blight in target land. +1 Damage per Blight in adjacent lands. -If you have- 3 Moon, 3 Earth: Repeat on an adjacent land.',
  },
  {
    name: 'Indomitable Claim',
    cost: 4,
    speed: 'Fast',
    elements: [
      'Sun',
      'Earth',
    ],
    description: 'Add 1 Presence in target land even if you normally could not due to land type. Defend 20. -If you have- 2 Sun, 3 Earth: 3 Fear if Invaders are present. Invaders skip all Actions in target land this turn.',
  },
  {
    name: 'Mists of Oblivion',
    cost: 4,
    speed: 'Slow',
    elements: [
      'Moon',
      'Air',
      'Water',
    ],
    description: '1 Fear per Town / City this Power destroys (to a maximum of 4). 1 Damage to each Invader. -If you have- 2 Moon, 3 Air, 2 Water: 3 Damage.',
  },
  {
    name: 'Dissolve the Bonds of Kinship',
    cost: 4,
    speed: 'Slow',
    elements: [
      'Fire',
      'Water',
      'Animal',
    ],
    description: 'Replace 1 City with 2 Explorer. Replace 1 Town with 1 Explorer. Replace 1 Dahan with 1 Explorer. Push all Explorer from target land to as many different lands as possible. -If you have- 2 Fire, 2 Water, 3 Animal: Before Pushing, Explorer and Town / City do Damage to each other.',
  },
  {
    name: 'Strangling Firevine',
    cost: 4,
    speed: 'Slow',
    elements: [
      'Fire',
      'Plant',
    ],
    description: 'Destroy all Explorer. Add 1 Wilds. Add 1 Wilds in the originating Sands. 1 Damage per Wilds in / adjacent to target land. -If you have- 2 Fire, 3 Plant: +1 Damage per Wilds in / adjacent to target land.',
  },
  {
    name: 'Bloodwrack Plague',
    cost: 4,
    speed: 'Fast',
    elements: [
      'Water',
      'Earth',
      'Animal',
    ],
    description: 'Add 2 Disease. For each Disease in target land, Defend 1 in target and all adjacent lands. -If you have- 2 Earth, 4 Animal: 2 Fear. For each Disease in target land do 1 Damage in target or an adjacent land.',
  },
  {
    name: 'Death Falls Gently from Open Blossoms',
    cost: 4,
    speed: 'Slow',
    elements: [
      'Moon',
      'Air',
      'Plant',
    ],
    description: '4 Damage. If any Invaders remain, add 1 Disease. -If you have- 3 Air, 3 Plant: 3 Fear. Add 1 Disease to 2 adjacent lands with Invaders.',
  },
  {
    name: 'Grant Hatred a Ravenous Form',
    cost: 4,
    speed: 'Slow',
    elements: [
      'Moon',
      'Fire',
    ],
    description: 'For each Strife / Blight in target land, 1 Fear and 2 Damage. If this destroys all invaders in target land, add 1 Beasts. -If you have- 4 Moon, 2 Fire: Add 1 Strife in up to 3 adjacent lands.',
  },
  {
    name: 'Insatiable Hunger of the Swarm',
    cost: 4,
    speed: 'Fast',
    elements: [
      'Air',
      'Plant',
      'Animal',
    ],
    description: 'Add 1 Blight. Add 2 Beasts. Gather up to 2 Beasts. Each Beasts deal 1 Fear, 2 Damage to Invaders and 2 Damage to Dahan. Destroy 1 Beasts. -If you have- 2 Air, 4 Animal: Repeat this Power on an adjacent land.',
  },
  {
    name: 'Instruments of their own Ruin',
    cost: 4,
    speed: 'Fast',
    elements: [
      'Sun',
      'Fire',
      'Air',
      'Animal',
    ],
    description: 'Add 1 Strife. Each Invader with Strife deals Damage to other Invaders in target land. -If you have- 4 Sun, 2 Fire, 2 Animal: Instead, if Invaders Ravage in target land, they damage Invaders in adjacent lands instead of Dahan and the land. Dahan in target land do not fight back.',
  },
  {
    name: 'Unrelenting Growth',
    cost: 4,
    speed: 'Slow',
    elements: [
      'Sun',
      'Fire',
      'Water',
      'Plant',
    ],
    description: 'Target Spirit adds 2 Presence and 1 Wilds to a land at 1 Range. -If you have- 3 Sun, 3 Plant: In that land, add 1 additional Wilds and remove 1 Blight. Target Spirit gains a Power Card.',
  },
  {
    name: 'Sweep into the Sea',
    cost: 4,
    speed: 'Slow',
    elements: [
      'Sun',
      'Air',
      'Water',
    ],
    description: 'Push all Explorer and Town one land towards the nearest Ocean. -or- If target land is Coastal, destroy all Explorer and Town. -If you have- 3 Sun, 2 Water: Repeat on an adjacent land.',
  },
  {
    name: 'Unlock the Gates of Deepest Power',
    cost: 4,
    speed: 'Fast',
    elements: [
      'Sun',
      'Moon',
      'Fire',
      'Air',
      'Water',
      'Earth',
      'Plant',
      'Animal',
    ],
    description: 'Target Spirit gains a Major Power by drawing 2 and keeping 1, without having to Forget another Power Card. -If you have- 2 Sun, 2 Moon, 2 Fire, 2 Air, 2 Water, 2 Earth, 2 Plant, 2 Animal: Target Spirit may now play the Major Power they keep by paying half its cost (round up) OR by Forgetting it at the end of turn. It gains all elemental thresholds.',
  },
  {
    name: 'Forests of Living Obsidian',
    cost: 4,
    speed: 'Slow',
    elements: [
      'Sun',
      'Fire',
      'Earth',
      'Plant',
    ],
    description: 'Add 1 Badlands. Push all Dahan. 1 Damage to each Invader. If the origin land is your Sacred Site, +1 Damage to each Invader.  -If you have- 2 Sun, 3 Fire, 3 Earth: Repeat this Power.',
  },
  {
    name: 'Infestation of Venomous Spiders',
    cost: 4,
    speed: 'Fast',
    elements: [
      'Air',
      'Earth',
      'Plant',
      'Animal',
    ],
    description: 'Add 1 Beasts. Gather up to 1 Beasts. For each Beasts, 1 Fear (max. 4) and Invaders skip one Action in target land. -If you have- 2 Air, 2 Earth, 3 Animal; After this Power causes Invaders to skip an Action, 4 Damage.',
  },
  {
    name: 'Walls of Rock and Thorn',
    cost: 4,
    speed: 'Fast',
    elements: [
      'Sun',
      'Earth',
      'Plant',
    ],
    description: '2 Damage. Defend 8. Add 1 Wilds. Isolate target land. -If you have- 2 Earth, 2 Plant: +2 Damage. +2 Defend. Add 1 Badlands.',
  },
  {
    name: 'The Wounded Wild Turns on its Assailants',
    cost: 4,
    speed: 'Slow',
    elements: [
      'Fire',
      'Plant',
      'Animal',
    ],
    description: 'Add 2 Badlands. Gather up to 2 Beasts. 1 Damage per Blight / Beasts / Wilds. -If you have- 2 Fire, 3 Plant, 2 Animal: 2 Fear per Invader destroyed by the Power (max. 8 Fear).',
  },
  {
    name: 'Utter a Curse of Dread and Bone',
    cost: 4,
    speed: 'Slow',
    elements: [
      'Moon',
      'Animal',
    ],
    description: 'For each Blight in / adjacent to target land, add 1 Badlands, 1 Disease, or 1 Strife. (Max. +3 of each.) Then: 2 Fear. 1 Damage. -If you have- 3 Moon, 2 Animal: For each type of token you added, add 1 more within 1 Range. 1 Damage in an adjacent land.',
  },
  {
    name: 'Weave Together the Fabric of Place',
    cost: 4,
    speed: 'Fast',
    elements: [
      'Sun',
      'Moon',
      'Air',
      'Water',
      'Earth',
    ],
    description: 'Target land and a land adjacent to it become a single land for this turn. (It has the terrain and land # of both lands. When this effect expires, divide pieces as you wish; all of them are considered moved.) -If you have- 4 Air: Isolate the joined land. If it has Invaders, 2 Fear, and remove up to 2 Invaders.',
  },
  {
    name: 'Melt Earth into Quicksand',
    cost: 4,
    speed: 'Fast',
    elements: [
      'Moon',
      'Water',
      'Earth',
    ],
    description: '1 Fear. 2 Damage. Isolate target land. After Invaders / Dahan are Moved into target land, Destroy them.  -If you have- 2 Moon, 4 Water, 2 Earth: +4 Damage. Add 1 Badlands. Add 1 Wilds.',
  },
  {
    name: 'Cleansing Floods',
    cost: 5,
    speed: 'Slow',
    elements: [
      'Sun',
      'Water',
    ],
    description: '4 Damage. Remove 1 Blight. -If you have- 4 Water: +10 Damage.',
  },
  {
    name: 'Pillar of Living Flame',
    cost: 5,
    speed: 'Slow',
    elements: [
      'Fire',
    ],
    description: '3 Fear. 5 Damage. If target land is Jungle / Wetland, add 1 Blight. -If you have- 4 Fire: +2 Fear and +5 Damage.',
  },
  {
    name: 'Blazing Renewal',
    cost: 5,
    speed: 'Fast',
    elements: [
      'Fire',
      'Earth',
      'Plant',
    ],
    description: 'Target Spirit adds 2 of their destroyed Presence into a single land, up to 2 Range from your Presence. If any Presence was added, 2 damage to each Town / City in that land. -If you have- 3 Fire, 3 Earth, 2 Plant: 4 Damage in that land.',
  },
  {
    name: 'Sea Monsters',
    cost: 5,
    speed: 'Slow',
    elements: [
      'Water',
      'Animal',
    ],
    description: 'Add 1 Beasts. If Invaders are present, 2 Fear per Beasts (max. 8 Fear). 3 Damage per Beasts. 1 Damage per Blight. -If you have- 3 Water, 3 Animal: Repeat this power.',
  },
  {
    name: 'Twisted Flowers Murmur Ultimatums',
    cost: 5,
    speed: 'Slow',
    elements: [
      'Sun',
      'Moon',
      'Air',
      'Earth',
      'Plant',
    ],
    description: '4 Fear. Add 1 Strife. If the Terror Level is 2 or higher, remove 2 Invaders. -If you have- 3 Moon, 2 Air, 3 Plant: +3 Fear, before the Terror Level check. 3 Damage.',
  },
  {
    name: 'Focus the Land\'s Anguish',
    cost: 5,
    speed: 'Slow',
    elements: [
      'Sun',
    ],
    description: 'If this Power Destroys any Town / City, 5 Fear. Gather up to 5 Blight. 1 Damage per Blight.  -If you have- 3 Sun: +1 Damage per Blight.',
  },
  {
    name: 'Spill Bitterness into the Earth',
    cost: 5,
    speed: 'Fast',
    elements: [
      'Fire',
      'Water',
      'Earth',
    ],
    description: '6 Damage. Add 2 Badlands / Strife and 1 Blight. In up to 3 adjacent lands with Blight, add 1 Badlands / Strife. -If you have- 3 Fire, 3 Water: In up to 3 adjacent lands, 1 Damage to each Invader.',
  },
  {
    name: 'Talons of Lightning',
    cost: 6,
    speed: 'Fast',
    elements: [
      'Fire',
      'Air',
    ],
    description: '3 Fear. 5 Damage. -If you have- 3 Fire, 3 Air: Destroy 1 Town in each adjacent land. Increase this power\'s Range to 3 Range.',
  },
  {
    name: 'Tsunami',
    cost: 6,
    speed: 'Slow',
    elements: [
      'Water',
      'Earth',
    ],
    description: '2 Fear. 8 Damage. Destroy 2 Dahan. -If you have- 3 Water, 2 Earth: In each otdher Coastal land on the same board: 1 Fear, 4 Damage, and Destroy 1 Dahan.',
  },
  {
    name: 'Manifest Incarnation',
    cost: 6,
    speed: 'Slow',
    elements: [
      'Sun',
      'Moon',
      'Earth',
      'Animal',
    ],
    description: '6 Fear. +1 Fear for each Town / City and for each of your Presence in target land. Remove 1 City, 1 Town and 1 Explorer. Then Invaders in target land Ravage. -If you have- 3 Sun, 3 Moon: +3 Fear. Invaders do -6 Damage on their Ravage.',
  },
  {
    name: 'Dream of the Untouched Land',
    cost: 6,
    speed: 'Fast',
    elements: [
      'Moon',
      'Water',
      'Earth',
      'Plant',
      'Animal',
    ],
    description: 'Remove up to 3 Blight and up to 3 Health worth of Invaders.  -If you have- 3 Moon, 2 Water, 3 Earth, 2 Plant: (Max. 1x/game) Add a random new Island Board next to target board. Ignore its Setup icons; add 2 Beasts, 2 Wilds, 2 Badlands and up to 2 Presence (from any Spirits) anywhere on it. From now on, Build cards and "Each board / Each land" Adversary Actions skip 1 Board.',
  },
  {
    name: 'Transform to a Murderous Darkness',
    cost: 6,
    speed: 'Slow',
    elements: [
      'Moon',
      'Fire',
      'Air',
      'Water',
      'Plant',
    ],
    description: 'Target Spirit may choose one of their Sacred Sites. In that land: Replace all their Presence with Badlands; the replaced Presence leave the game. Push any number of those Badlands. 3 Fear. 3 Damage per Presence replaced. -If you have- 3 Moon, 2 Fire, 2 Air: 1 Damage in an adjacent land. 1 Damage in an adjacent land.',
  },
  {
    name: 'Irresistible Call',
    cost: 6,
    speed: 'Fast',
    elements: [
      'Sun',
      'Air',
      'Plant',
    ],
    description: 'Gather 5 Town, 5 Dahan, 5 Beasts, and 15 Explorer. -If you have- 2 Sun, 3 Air, 2 Plant: Invaders skip all Actions in target land. Isolate target land.',
  },
  {
    name: 'Fire and Flood',
    cost: 7,
    speed: 'Slow',
    elements: [
      'Sun',
      'Fire',
      'Water',
    ],
    description: '4 Damage in each target land. (Range must be measured from the same SacredSite.) -If you have- 3 Fire: +4 Damage in either target land. 3 Water: +4 Damage in either target land.',
  },
  {
    name: 'Volcanic Eruption',
    cost: 8,
    speed: 'Slow',
    elements: [
      'Fire',
      'Earth',
    ],
    description: '6 Fear. 20 Damage. Destroy all Dahan and Beasts. Add 1 Blight. -If you have- 4 Fire, 3 Earth: Destroy all Invaders. Add 1 Wilds. In each adjacent land: 10 Damage. Destroy all Dahan and Beasts. If there are no Blight, add 1 Blight.',
  },
  {
    name: 'Draw Towards a Consuming Void',
    cost: 8,
    speed: 'Slow',
    elements: [
      '',
    ],
    description: 'Gather 1 Explorer, Town, City, Dahan, Presence, and Beasts from each adjacent land. 4 Fear. 15 Damage. 5 Damage to Dahan. Destroy 1 Presence from each Spirit. Remove 2 Beasts. -If you have- If you have no other power cards in play: Any number of times: Forget a Minor Power, a Major Power, and a Unique Power to perform the above effects again.',
  },
  {
    name: 'Cast down into the Briny Deep',
    cost: 9,
    speed: 'Slow',
    elements: [
      'Sun',
      'Moon',
      'Water',
      'Earth',
    ],
    description: '6 Fear. Destroy all Invaders. -If you have- 2 Sun, 2 Moon, 4 Water, 4 Earth: Destroy the board containing target land and everything on that board. All destroyed Blight is removed from the game instead of being returned to the Blight Card.',
  },
]
export const EVENT_CARDS: Array<{name: string}> = [
  { "name": "bureaucrats_adjust_funding" },
  { "name": "cities_rise" },
  { "name": "civic_engagement" },
  { "name": "coastal_towns_multiply" },
  { "name": "cultural_assimilation" },
  { "name": "dahan_trade_with_the_invaders" },
  { "name": "distant_exploration" },
  { "name": "eager_explorers" },
  { "name": "fortuneseekers" },
  { "name": "gradual_corruption" },
  { "name": "harvest_bounty_harvest_dust" },
  { "name": "heavy_farming" },
  { "name": "interesting_discoveries" },
  { "name": "invaders_surge_inland" },
  { "name": "invested_aristocracy" },
  { "name": "investigation_of_dangers" },
  { "name": "lifes_balance_tilts" },
  { "name": "mapmakers_chart_the_wild" },
  { "name": "missionaries_arrive" },
  { "name": "new_species_spread" },
  { "name": "no_bravery_without_numbers" },
  { "name": "overconfidence" },
  { "name": "population_rises" },
  { "name": "promising_farmland" },
  { "name": "provincial_seat" },
  { "name": "pull_together_in_adversity" },
  { "name": "putting_down_roots" },
  { "name": "relentless_optimism" },
  { "name": "remnants_of_a_spirits_heart" },
  { "name": "resourceful_populace" },
  { "name": "rising_interest_in_the_island" },
  { "name": "sacred_sites_under_threat" },
  { "name": "search_for_new_lands" },
  { "name": "seeking_the_interior" },
  { "name": "seek_new_farmland" },
  { "name": "smaller_ports_spring_up" },
  { "name": "sprawl_contained_by_the_wilds" },
  { "name": "strange_tales_attract_explorers" },
  { "name": "temporary_truce" },
  { "name": "the_frontier_calls" },
  { "name": "the_struggles_of_growth" },
  { "name": "thriving_trade" },
  { "name": "tightknit_communities" },
  { "name": "urban_development" },
  { "name": "wellprepared_explorers" },
  { "name": "wounded_lands_attract_explorers" }
]
export const FEAR_CARDS: Array<{
  name: string
}> = [
  {name: 'angry_mobs'},
  {name: 'avoid_the_dahan'},
  {name: 'belief_takes_root'},
  {name: 'beset_by_many_troubles'},
  {name: 'communities_in_disarray'},
  {name: 'dahan_attack'},
  {name: 'dahan_enheartened'},
  {name: 'dahan_on_their_guard'},
  {name: 'dahan_raid'},
  {name: 'dahan_reclaim_fishing_grounds'},
  {name: 'dahan_threaten'},
  {name: 'demoralized'},
  {name: 'depart_the_dangerous_land'},
  {name: 'depopulation'},
  {name: 'discord'},
  {name: 'emigration_accelerates'},
  {name: 'explorers_are_reluctant'},
  {name: 'fear_of_the_unseen'},
  {name: 'flee_from_dangerous_lands'},
  {name: 'flee_the_pestilent_land'},
  {name: 'immigration_slows'},
  {name: 'isolation'},
  {name: 'mimic_the_dahan'},
  {name: 'nerves_fray'},
  {name: 'overseas_trade_seem_safer'},
  {name: 'panic'},
  {name: 'panicked_by_wild_beasts'},
  {name: 'plan_for_departure'},
  {name: 'quarantine'},
  {name: 'retreat'},
  {name: 'scapegoats'},
  {name: 'seek_safety'},
  {name: 'sense_of_dread'},
  {name: 'spreading_timidity'},
  {name: 'tall_tales_of_savagery'},
  {name: 'theological_strife'},
  {name: 'too_many_monsters'},
  {name: 'trade_suffers'},
  {name: 'tread_carefully'},
  {name: 'unrest'},
  {name: 'wary_of_the_interior'},
]
